import { useMemo, useState } from 'react'
import { ScreenFrame } from './components/ScreenFrame'
import { Sidebar } from './components/Sidebar'
import { HandoffPanel } from './components/HandoffPanel'
import type { Locale, PlaygroundState, Screen } from './components/types'
import './App.css'

const screens: Screen[] = [
  { id: 'sk-landing-with-card', title: 'SK landing page with card', meta: 'consumer view' },
  { id: 'share-dialog-initial', title: 'Share dialog: email entry', meta: 'pop-up state 1' },
  { id: 'share-dialog-submitting', title: 'Share dialog: submitting', meta: 'pop-up state 2' },
  { id: 'share-dialog-success', title: 'Share dialog: success', meta: 'pop-up state 3 (link revealed)' },
  { id: 'share-dialog-error-rate', title: 'Share dialog: rate limited', meta: 'pop-up error state' },
  { id: 'share-dialog-error-revoked', title: 'Share dialog: token revoked', meta: 'pop-up error state' },
  { id: 'email-conversion-stub', title: 'Conversion email - stub user', meta: 'sign-up CTA' },
  { id: 'email-conversion-real', title: 'Conversion email - real user', meta: 'sign-in CTA' },
  { id: 'sa-signup-claim', title: 'SA signup landing (claim)', meta: 'after clicking email link' },
]

const translations: Record<Locale, Record<string, string>> = {
  en: {
    productName: 'Aerolite Air Purifier 3000',
    productPrice: 'RM 459.00',
    productMeta: 'Authentic - Verified by SmartKood',
    earnTitle: 'Earn affiliate commission',
    earnRate: 'Earn ${rate}%',
    earnDesc: 'Share this product with friends. When they buy, you earn commission.',
    affiliateBadge: 'Become an affiliate',
    affiliateHeroTitle: 'Earn {amount} or more by sharing this product',
    affiliateHeroDesc: 'When 10 friends buy through your link, rewards land in your wallet automatically.',
    affiliatePerSaleLabel: 'Per successful purchase',
    affiliateFlowShare: 'Share',
    affiliateFlowBuy: 'Friend buys',
    affiliateFlowEarn: 'Earn',
    affiliateFootnote: 'Rewards are credited automatically once the order is confirmed.',
    affiliateCta: 'Start earning now',
    shareNow: 'Share Now',
    dialogTitle: 'Share & earn',
    dialogHelper: "Enter your email. We'll send you a link to share. When someone buys via your link, you earn ${rate}% commission.",
    emailLabel: 'Your email address',
    submit: 'Get my link',
    cancel: 'Cancel',
    successTitle: 'Your share link is ready',
    successCommission: "You'll earn ${rate}% on every purchase",
    copy: 'Copy link',
    copied: 'Copied!',
    whatsapp: 'WhatsApp',
    facebook: 'Facebook',
    telegram: 'Telegram',
    nativeShare: 'More apps...',
    others: 'See all',
    done: 'Done',
    errorRateLimited: 'Too many requests. Try again in 60 seconds.',
    errorRevoked: 'This affiliate share is currently unavailable. Please contact the brand.',
    submitting: 'Generating your link...',
    emailUsedFor: "We'll email ${email} when someone buys.",
    emailConvSubject: 'You earned RM ${conv} from your share!',
    emailConvHello: 'Hi there!',
    emailConvBody: 'Someone made a purchase using your affiliate link for ${product}. You earned RM ${conv} in commission.',
    emailConvBalanceLabel: 'You have unclaimed money',
    emailConvCtaStub: 'Sign up to claim your balance',
    emailConvCtaReal: 'Sign in to claim your balance',
    emailConvFooter: "You're receiving this because someone shared an affiliate link from this email address. To stop receiving these or delete your data, contact SmartAffiliate support.",
    signupWelcome: 'Welcome!',
    signupClaimSub: 'Set up your SmartAffiliate account to claim your earnings.',
    signupBalanceLabel: 'You have unclaimed money',
    signupEmail: 'Email',
    signupPassword: 'Set a password',
    signupConfirm: 'Confirm password',
    signupContinue: 'Create account & claim',
    sellerWidgetTitle: 'Affiliate widget tokens',
    sellerWidgetSub: 'Generate tokens to embed in SmartKood landing pages. Each token is bound to one product.',
    issueWidget: 'Issue widget token',
    tableToken: 'Token',
    tableProduct: 'Product',
    tableLabel: 'Label',
    tableStatus: 'Status',
    tableShares: 'Shares',
    tableLastUsed: 'Last used',
    tableActions: 'Actions',
    statusActive: 'active',
    statusRevoked: 'revoked',
    actCopy: 'Copy',
    actEdit: 'Edit',
    actRegen: 'Regenerate',
    actRevoke: 'Revoke',
    issueModalTitle: 'Issue new widget token',
    issueModalSub: 'Pick the product this widget will share. The token grants permission to mint affiliate links for this specific product.',
    productPicker: 'Product',
    optionalLabel: 'Label (optional, for your records)',
    optionalExpiry: 'Expires (optional)',
    issueBtn: 'Issue token',
    tokenCreatedLabel: 'Token created - copy now',
    tokenReminder: 'Paste this into your SmartKood card config. You can re-copy this token anytime from the list above.',
    customerportalEditorTitle: 'Product Landing Page - Layout Editor',
    paletteTitle: 'Card Types',
    settingsTitle: 'Card Settings',
    selectedAffiliateShare: 'Affiliate Share Card',
    settingsTokenLabel: 'Widget Token',
    settingsTokenHelper: 'Paste the token from your SmartAffiliate seller portal',
    settingsLabelLabel: 'Display Label (Optional)',
    settingsLabelHelper: 'Leave blank to use the default headline',
    featureGateBadge: 'Feature enabled for this brand',
  },
  ms: {
    productName: 'Penapis Udara Aerolite 3000',
    productPrice: 'RM 459.00',
    productMeta: 'Tulen - Disahkan oleh SmartKood',
    earnTitle: 'Dapatkan komisen afiliat',
    earnRate: 'Dapat ${rate}%',
    earnDesc: 'Kongsi produk ini dengan rakan. Apabila mereka membeli, anda dapat komisen.',
    affiliateBadge: 'Jadi affiliate',
    affiliateHeroTitle: 'Dapat {amount} atau lebih dengan kongsi produk ini',
    affiliateHeroDesc: 'Apabila 10 rakan membeli melalui link anda, ganjaran masuk wallet secara automatik.',
    affiliatePerSaleLabel: 'Setiap pembelian berjaya',
    affiliateFlowShare: 'Kongsi',
    affiliateFlowBuy: 'Rakan beli',
    affiliateFlowEarn: 'Jana',
    affiliateFootnote: 'Ganjaran dikreditkan secara automatik sebaik sahaja pesanan disahkan.',
    affiliateCta: 'Mula jana sekarang',
    shareNow: 'Kongsi Sekarang',
    dialogTitle: 'Kongsi & dapat komisen',
    dialogHelper: 'Masukkan e-mel anda. Kami akan hantar pautan untuk dikongsi. Apabila seseorang beli melalui pautan, anda dapat ${rate}% komisen.',
    emailLabel: 'Alamat e-mel anda',
    submit: 'Dapatkan pautan',
    cancel: 'Batal',
    successTitle: 'Pautan kongsi anda sudah sedia',
    successCommission: 'Anda akan dapat ${rate}% bagi setiap pembelian',
    copy: 'Salin pautan',
    copied: 'Disalin!',
    whatsapp: 'WhatsApp',
    facebook: 'Facebook',
    telegram: 'Telegram',
    nativeShare: 'Lebih banyak apl...',
    others: 'Lihat semua',
    done: 'Selesai',
    errorRateLimited: 'Terlalu banyak permintaan. Cuba lagi dalam 60 saat.',
    errorRevoked: 'Perkongsian afiliat ini tidak tersedia sekarang. Sila hubungi jenama.',
    submitting: 'Menjana pautan anda...',
    emailUsedFor: 'Kami akan e-mel ${email} apabila seseorang membeli.',
    emailConvSubject: 'Anda dapat RM ${conv} dari perkongsian anda!',
    emailConvHello: 'Helo!',
    emailConvBody: 'Seseorang membuat pembelian menggunakan pautan afiliat anda untuk ${product}. Anda dapat RM ${conv} komisen.',
    emailConvBalanceLabel: 'Anda ada wang belum dituntut',
    emailConvCtaStub: 'Daftar untuk menuntut baki anda',
    emailConvCtaReal: 'Log masuk untuk tuntut baki anda',
    emailConvFooter: 'Anda menerima e-mel ini kerana seseorang berkongsi pautan afiliat dari alamat e-mel ini. Untuk berhenti atau padam data, hubungi sokongan SmartAffiliate.',
    signupWelcome: 'Selamat datang!',
    signupClaimSub: 'Sediakan akaun SmartAffiliate untuk menuntut pendapatan anda.',
    signupBalanceLabel: 'Anda ada wang belum dituntut',
    signupEmail: 'E-mel',
    signupPassword: 'Tetapkan kata laluan',
    signupConfirm: 'Sahkan kata laluan',
    signupContinue: 'Cipta akaun & tuntut',
    sellerWidgetTitle: 'Token widget afiliat',
    sellerWidgetSub: 'Hasilkan token untuk dibenamkan dalam halaman pendaratan SmartKood. Setiap token terikat kepada satu produk.',
    issueWidget: 'Hasilkan token widget',
    tableToken: 'Token',
    tableProduct: 'Produk',
    tableLabel: 'Label',
    tableStatus: 'Status',
    tableShares: 'Perkongsian',
    tableLastUsed: 'Guna terakhir',
    tableActions: 'Tindakan',
    statusActive: 'aktif',
    statusRevoked: 'dibatalkan',
    actCopy: 'Salin',
    actEdit: 'Edit',
    actRegen: 'Jana semula',
    actRevoke: 'Batal',
    issueModalTitle: 'Hasilkan token widget baru',
    issueModalSub: 'Pilih produk yang akan dikongsi widget ini. Token ini memberi kebenaran untuk menjana pautan afiliat untuk produk tertentu ini.',
    productPicker: 'Produk',
    optionalLabel: 'Label (pilihan, untuk rekod anda)',
    optionalExpiry: 'Tamat tempoh (pilihan)',
    issueBtn: 'Hasilkan token',
    tokenCreatedLabel: 'Token dijana - salin sekarang',
    tokenReminder: 'Tampal ini ke dalam konfigurasi kad SmartKood anda. Anda boleh menyalin token ini bila-bila masa dari senarai di atas.',
    customerportalEditorTitle: 'Halaman Pendaratan Produk - Editor Susun Atur',
    paletteTitle: 'Jenis Kad',
    settingsTitle: 'Tetapan Kad',
    selectedAffiliateShare: 'Kad Perkongsian Afiliat',
    settingsTokenLabel: 'Token Widget',
    settingsTokenHelper: 'Tampal token dari portal penjual SmartAffiliate anda',
    settingsLabelLabel: 'Label Paparan (Pilihan)',
    settingsLabelHelper: 'Biarkan kosong untuk menggunakan tajuk lalai',
    featureGateBadge: 'Ciri didayakan untuk jenama ini',
  },
  'zh-CN': {
    productName: 'Aerolite 空气净化器 3000',
    productPrice: 'RM 459.00',
    productMeta: '正品 - 由 SmartKood 验证',
    earnTitle: '赚取联盟佣金',
    earnRate: '赚取 ${rate}%',
    earnDesc: '把这个产品分享给朋友。朋友购买后，你就能获得佣金。',
    shareNow: '立即分享',
    dialogTitle: '分享并赚取佣金',
    dialogHelper: '输入你的电邮。我们会发送可分享的链接给你。有人通过你的链接购买时，你将获得 ${rate}% 佣金。',
    emailLabel: '你的电邮地址',
    submit: '获取我的链接',
    cancel: '取消',
    successTitle: '你的分享链接已准备好',
    successCommission: '每次购买你都将获得 ${rate}%',
    copy: '复制链接',
  copied: '已复制！',
    whatsapp: 'WhatsApp',
    facebook: 'Facebook',
    telegram: 'Telegram',
    nativeShare: '更多应用...',
  others: '查看全部',
    done: '完成',
    errorRateLimited: '请求过多。请在 60 秒后再试。',
    errorRevoked: '此联盟分享目前不可用。请联系品牌方。',
    submitting: '正在生成你的链接...',
    emailUsedFor: '有人购买时，我们会发送电邮到 ${email}。',
    emailConvSubject: '你通过分享赚取了 RM ${conv}！',
    emailConvHello: '你好！',
    emailConvBody: '有人通过你为 ${product} 分享的联盟链接完成了购买。你赚取了 RM ${conv} 佣金。',
    emailConvBalanceLabel: '你有尚未领取的钱',
    emailConvCtaStub: '注册以领取余额',
    emailConvCtaReal: '登录以领取余额',
    emailConvFooter: '你收到这封电邮，是因为有人使用此电邮地址分享了联盟链接。如需停止接收或删除数据，请联系 SmartAffiliate 支持。',
    signupWelcome: '欢迎！',
    signupClaimSub: '设置你的 SmartAffiliate 账户以领取收益。',
    signupBalanceLabel: '你有尚未领取的钱',
    signupEmail: '电邮',
    signupPassword: '设置密码',
    signupConfirm: '确认密码',
    signupContinue: '创建账户并领取',
    sellerWidgetTitle: '联盟小组件令牌',
    sellerWidgetSub: '生成令牌并嵌入 SmartKood 落地页。每个令牌绑定一个产品。',
    issueWidget: '生成小组件令牌',
    tableToken: '令牌',
    tableProduct: '产品',
    tableLabel: '标签',
    tableStatus: '状态',
    tableShares: '分享数',
    tableLastUsed: '最后使用',
    tableActions: '操作',
    statusActive: '启用',
    statusRevoked: '已撤销',
    actCopy: '复制',
    actEdit: '编辑',
    actRegen: '重新生成',
    actRevoke: '撤销',
    issueModalTitle: '生成新的小组件令牌',
    issueModalSub: '选择此小组件要分享的产品。该令牌允许为指定产品生成联盟链接。',
    productPicker: '产品',
    optionalLabel: '标签（可选，用于记录）',
    optionalExpiry: '到期日（可选）',
    issueBtn: '生成令牌',
    tokenCreatedLabel: '令牌已生成 - 立即复制',
    tokenReminder: '将此令牌粘贴到你的 SmartKood 卡片配置中。之后也可以随时从列表重新复制。',
    customerportalEditorTitle: '产品落地页 - 布局编辑器',
    paletteTitle: '卡片类型',
    settingsTitle: '卡片设置',
    selectedAffiliateShare: '联盟分享卡片',
    settingsTokenLabel: '小组件令牌',
    settingsTokenHelper: '从你的 SmartAffiliate 卖家门户复制令牌并粘贴到这里',
    settingsLabelLabel: '显示标签（可选）',
    settingsLabelHelper: '留空则使用默认标题',
    featureGateBadge: '此品牌已启用该功能',
  },
}

const zhAffiliateTranslations: Record<string, string> = {
  affiliateBadge: '成为分销伙伴',
  affiliateHeroTitle: '分享此产品，赚取 {amount} 或更多',
  affiliateHeroDesc: '10 位朋友通过你的链接购买，奖励自动到账。',
  affiliatePerSaleLabel: '每笔成功购买',
  affiliateFlowShare: '分享',
  affiliateFlowBuy: '朋友购买',
  affiliateFlowEarn: '赚取',
  affiliateFootnote: '订单确认后，奖励将自动入账。',
}

zhAffiliateTranslations.affiliateCta = '??????'

function App() {
  const [state, setState] = useState<PlaygroundState>({
    screen: 'sk-landing-with-card',
    locale: 'en',
    balance: 42,
    rate: 5,
    lastConv: 22,
  })
  const screen = screens.find((item) => item.id === state.screen) ?? screens[0]
  const t = useMemo(() => makeTranslator(state), [state])

  return (
    <div className="wireframe-app">
      <Sidebar screens={screens} state={state} setState={setState} />
      <main className="main">
        <section className="stage" aria-label="Selected wireframe screen">
          <ScreenFrame screen={screen} state={state} t={t} />
        </section>
      </main>
      <HandoffPanel screen={state.screen} />
    </div>
  )
}

function makeTranslator(state: PlaygroundState) {
  return (key: string) => {
    const value = (state.locale === 'zh-CN' ? zhAffiliateTranslations[key] : undefined)
      ?? translations[state.locale][key]
      ?? translations.en[key]
      ?? key
    return value
      .replaceAll('${rate}', String(state.rate))
      .replaceAll('${balance}', state.balance.toFixed(2))
      .replaceAll('${conv}', state.lastConv.toFixed(2))
      .replaceAll('${email}', 'aishah@example.com')
      .replaceAll('${product}', translations[state.locale].productName)
      .replaceAll('${price}', translations[state.locale].productPrice)
  }
}

export default App
